### ISSUE TITLE
[Bug] SHA-1 and MD5 hashes are never calculated

### ISSUE THREAD

**Issue by DerekTurtleRoe** [mroach/n64-go#8]
For some reason no ROM that I try with ROM64 seems to calculate the SHA-1 or MD5 hash. It just says "not calculated".

This happened with big-endian, byte-swapped, and little-endian ROMs.

All of the tested ROMs were No-Intro verified, or checked using [romjudge ](https://github.com/jkbenaim/romjudge)and work on emulators and flash carts.

Side note, the text output puts the CRC1 and CRC2 twice in the outputted text, which is redundant I believe.

**Comment by mroach** [comment]
Please include the command you were running when you had this problem.

**Comment by mroach** [comment]
The CRC1/2 do appear twice in `--output text` mode but they don't come from the same source. Under the `Checksums` heading, this is the CRC1/2 as calcualted by rom64. Under the `ROM` heading, these are the CRC1/2 as reported by the ROM file itself.

**Comment by DerekTurtleRoe** [comment]
Sorry, I was using the `ls` command and with `--output text` was what I noticed was having the issue specifically.

I didn't realize there were multiple ways of acquiring the CRC1 and CRC2, so that's my bad. Is it common for the CRC1 and CRC2 to be different based on what method you use to calculate or retrieve it?

**Comment by mroach** [comment]
Ah, now I see how you were able to encounter "Not Calculated". Checksum calculation is not done unless explicitly needed since it creates an appreciable delay and CPU work with large directories of roms. Originally `ls` only output in table format, so it would only calculate those checksums if the columns were asked for with the `--columns` flag, The `text`, `json`, and `xml` formats are "static" in that you can't pick the fields you want returned like with `table`, `tab`, and `csv` format, so we end up with a confusing issue here. 

The `--columns` flag can actually be used in this case to get the checksums to calculate.

```
rom64 ls ~/Downloads/n64 -o text -c file_md5,file_sha1,file_crc1,file_crc2
```

This also works for `json` and `xml` formats to get the checksums to calculate.

One option is to document this case and instruct users to use the `--columns` flag to get the calculations they want. Another is to always calculate them in `text`, `json`, and `xml` formats. The downside with that is creating a slowdown when users might not even want them.

**Comment by mroach** [comment]
For now I've updated the readme with a note about checksums and how to request them to be calculated.

As for the CRC1 and CRC2, in my experiences they have matched. Endianness shouldn't cause an issue since it's swapped to the native format internally when doing these calculations. If you have the calculated and reported CRCs mismatching, I'd be interested to see what other tools make of it.

When I was developing this I used another simple C program to compare the CRC results and I also compared to what I saw on EverDrive 64.

**Comment by DerekTurtleRoe** [comment]
> Ah, now I see how you were able to encounter "Not Calculated". Checksum calculation is not done unless explicitly needed since it creates an appreciable delay and CPU work with large directories of roms. Originally `ls` only output in table format, so it would only calculate those checksums if the columns were asked for with the `--columns` flag, The `text`, `json`, and `xml` formats are "static" in that you can't pick the fields you want returned like with `table`, `tab`, and `csv` format, so we end up with a confusing issue here.
> 
> The `--columns` flag can actually be used in this case to get the checksums to calculate.
> 
> ```
> rom64 ls ~/Downloads/n64 -o text -c file_md5,file_sha1,file_crc1,file_crc2
> ```
> 
> This also works for `json` and `xml` formats to get the checksums to calculate.
> 
> One option is to document this case and instruct users to use the `--columns` flag to get the calculations they want. Another is to always calculate them in `text`, `json`, and `xml` formats. The downside with that is creating a slowdown when users might not even want them.



> For now I've updated the readme with a note about checksums and how to request them to be calculated.
> 
> As for the CRC1 and CRC2, in my experiences they have matched. Endianness shouldn't cause an issue since it's swapped to the native format internally when doing these calculations. If you have the calculated and reported CRCs mismatching, I'd be interested to see what other tools make of it.
> 
> When I was developing this I used another simple C program to compare the CRC results and I also compared to what I saw on EverDrive 64.

Ah, that makes sense. I was a bit confused about why it wasn't calculating them since it didn't seem there was a way to set that as an option when using `ls`. 😄 

As for the CRC's, I was a bit worried about CRC clashing, but so far I haven't encountered any issues in the real world. There have been examples of bad dumps of certain software titles having the same CRC1 and CRC2 and causing issues in game databases who use that info to tell games apart, but that's the closest thing to that I've come.

Thanks for all your help and information! 😄

**Comment by mroach** [comment]
Now I'm not sure if I've understood your question about CRCs and if my answer added more confusion.

When a ROM dump is good, the CRC1 and 2 calculated by rom64 of the *File* should match what's in the *ROM* header. That's what we see with production game dumps anyway:

```
rom64 info ~/Downloads/Super\ Mario\ 64\ \(USA\).n64
File:
  Name:    Super Mario 64 (USA).n64
  Size:    8 MB
  Format:  v64 (Byte-swapped)
  Checksums:
    MD5:     165a9558b7539507e73e7afecffb200c
    SHA1:    1002dd7b56aa0a59a9103f1fb3d57d6b161f8da7
    CRC 1:   635A2BFF
    CRC 2:   8B022326

ROM:
  ID:        NSME
  Title:     SUPER MARIO 64
  Media:     Cartridge
  Region:    USA
  Video:     NTSC
  Version:   1.0
  CIC:       6102
  CRC 1:     635A2BFF
  CRC 2:     8B022326
```

By clash, do you mean two ROM files with different contents having the same CRC values? It's entirely possible that two different ROM files would have the same values in the *header*. There's nothing stopping anyone from just writing whatever CRC values into the header that they want. Just like how you could overwrite the title on a ROM with any data. Then sure, you could have different files with the same values in the headers.

As for the *calculated* CRCs of the file, those are highly unlikely to be the same for different files since it's a checksum of about ~1 MB of data in the file.

The SHA-1 and MD5 will never be the same between files unless those files have identical contents. The ROM validation data file built into rom64 uses SHA-1 validation.

**Comment by DerekTurtleRoe** [comment]
> Now I'm not sure if I've understood your question about CRCs and if my answer added more confusion.
> 
> When a ROM dump is good, the CRC1 and 2 calculated by rom64 of the _File_ should match what's in the _ROM_ header. That's what we see with production game dumps anyway:
> 
> ```
> rom64 info ~/Downloads/Super\ Mario\ 64\ \(USA\).n64
> File:
>   Name:    Super Mario 64 (USA).n64
>   Size:    8 MB
>   Format:  v64 (Byte-swapped)
>   Checksums:
>     MD5:     165a9558b7539507e73e7afecffb200c
>     SHA1:    1002dd7b56aa0a59a9103f1fb3d57d6b161f8da7
>     CRC 1:   635A2BFF
>     CRC 2:   8B022326
> 
> ROM:
>   ID:        NSME
>   Title:     SUPER MARIO 64
>   Media:     Cartridge
>   Region:    USA
>   Video:     NTSC
>   Version:   1.0
>   CIC:       6102
>   CRC 1:     635A2BFF
>   CRC 2:     8B022326
> ```
> 
> By clash, do you mean two ROM files with different contents having the same CRC values? It's entirely possible that two different ROM files would have the same values in the _header_. There's nothing stopping anyone from just writing whatever CRC values into the header that they want. Just like how you could overwrite the title on a ROM with any data. Then sure, you could have different files with the same values in the headers.
> 
> As for the _calculated_ CRCs of the file, those are highly unlikely to be the same for different files since it's a checksum of about ~1 MB of data in the file.
> 
> The SHA-1 and MD5 will never be the same between files unless those files have identical contents. The ROM validation data file built into rom64 uses SHA-1 validation.

Yeah, I understand what you're saying, I think I just worded it poorly or wasn't specific enough. CRC1 and CRC2 being the same is sort of common among the same official release, but every once in a while there is homebrew or something that will have the same CRC1 and CRC2 as a retail game which is confusing from my perspective of wanting to create a database for all the ROMs.

**Comment by DerekTurtleRoe** [comment]
I think this can be closed since the flag is available and this isn't really a bug. 😄

**Comment by mroach** [comment]
@DerekTurtleRoe Cool! Glad we were able to sort these issues out. Let me know if there's anything the program could do to make life easier. :) I'm thinking about making one for other systems next...

**Comment by DerekTurtleRoe** [comment]
> @DerekTurtleRoe Cool! Glad we were able to sort these issues out. Let me know if there's anything the program could do to make life easier. :) I'm thinking about making one for other systems next...

Can I ask what systems? I feel like more complete tools like this for other systems would be awesome! I would love to help in any way I can. 😄

**Comment by DerekTurtleRoe** [comment]
Also are Nintendo 64 Disk Drive, iQue, and Aleck64 games fully supported or only cartridge conversions? That could be something  to add. I suppose just adding the No-Intro database entries for them should be somewhat easy, not sure if the images themselves would need to be read differently for iQue and Aleck64. N64DD images are very different though, so it might be ambitious.
